steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    dir: 'helloworld'
    args: 
      - build
      - --no-cache
      - -t
      - ${_IMAGE}
      - .
  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args:
      - push
      - ${_IMAGE}
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE
      - --platform=managed
      - --image=${_IMAGE}
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - --region=${_REGION}
      - --quiet
    id: Deploy

substitutions:
  _SERVICE: hello-world
  _REGION: europe-west2
  _IMAGE: gcr.io/${PROJECT_ID}/${_SERVICE}:${TAG_NAME/helloworld\//}
options:
  dynamic_substitutions: true
