steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE}:${_VERSION}', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE}:${_VERSION}']

substitutions:
  _SERVICE: helloworld
  _VERSION: ${TAG_NAME/helloworld\//}
options:
  dynamic_substitutions: true
